"""Generated by foundry-tools: loot item Tool Test Note."""
from _items import build_generic

FOLDER = "Act 2 Road to Bridgehollow/Ossuary Exchange/Items"


def build(k):
    build_generic(k, {'shape': 'paper', 'w': 0.2, 'd': 0.28, 'h': 0.01, 'color': '#d8c9a0', 'texture': 'gen_tool_test_note.png'})
