"""Loot items: spec -> procedural 3D prop (Blender, via generators/_items.build_generic) -> dnd5e loot Item -> optional placement as a model Tile."""
import json
import subprocess

from .common import DEFAULT_FOLDER, GEN, OUT, ROOT, TEXTURES, bridge, folder_id, scene_frame, slug, to_scene
from .npc import fvtt

TEMPLATE = {
    "name": "Example Letter", "description": "Player-facing text only (no GM notes, so it can be dragged to a player's sheet).",
    "gm_notes": "GM-only: where it is found, DC, what it points to. Goes into the guide, never onto the item.",
    "shape": "paper", "w": 0.2, "d": 0.28, "h": 0.01, "color": "#d8c9a0", "text": "Line one\nLine two", "wall": False,
    "folder": "Quest Items (Side Quests)", "weight": 0, "price": 0, "rarity": "", "img": "icons/svg/book.svg",
}


def make_texture(spec):
    """Text printed on the prop's main face (paper, book cover, wall plate). Returns the PNG file name inside foundry-3d/textures."""
    from PIL import Image, ImageDraw, ImageFont
    plate = spec.get("shape") == "plate"
    w = max(64, int(spec.get("w", 0.1) * 1600))
    d = max(64, int(spec.get("h" if plate else "d", 0.1) * 1600))
    bg = spec.get("color", "#d8c9a0")
    img = Image.new("RGB", (w, d), bg)
    dr = ImageDraw.Draw(img)
    lines = spec.get("text", "").split("\n")
    size = max(12, int(min(w / max(6, max(len(ln) for ln in lines)) * 1.7, d / (len(lines) + 1))))
    fnt = ImageFont.truetype("C:/Windows/Fonts/georgiab.ttf", size)
    bright = sum(int(bg.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4)) > 380
    ink = "#2a1c0a" if bright else "#e8dcc0"
    y = d / 2 - (len(lines) - 1) * size * 0.6
    for ln in lines:
        dr.text((w / 2, y), ln, font=fnt, fill=ink, anchor="mm")
        y += size * 1.2
    name = f"gen_{slug(spec['name'])}.png"
    img.save(TEXTURES / name)
    return name


def build_model(spec, dry=False, log=print):
    """Write generators/item_<slug>.py (calls build_generic with the spec) and build it with make.ps1. Returns the model file name."""
    s = slug(spec["name"])
    params = {k: spec[k] for k in ("shape", "w", "d", "h", "color", "metal") if k in spec}
    if spec.get("text"):
        params["texture"] = f"gen_{s}.png" if dry else make_texture(spec)
    fname = f"item_{s}{spec.get('rev', '')}"                                   # bump 'rev' after a rebuild: browsers cache models by file name
    (GEN / f"{fname}.py").write_text(
        f'"""Generated by foundry-tools: loot item {spec["name"]}."""\nfrom _items import build_generic\n\nFOLDER = "{DEFAULT_FOLDER}/Items"\n\n\n'
        f"def build(k):\n    build_generic(k, {params!r})\n", encoding="utf-8")
    if not dry:
        subprocess.run(["powershell", "-NoProfile", "-File", str(ROOT / "foundry-3d" / "make.ps1"), fname], check=True, cwd=str(ROOT / "foundry-3d"), capture_output=True)
        log(f"model built: {fname}.glb")
    return f"{fname}.glb"


def build_item_doc(spec, model_file):
    return {"name": spec["name"], "type": "loot", "img": spec.get("img", "icons/svg/book.svg"),
            "system": {"description": {"value": fvtt.p(spec.get("description", "")), "chat": ""},
                       "source": {"custom": "Varrenmoor (generated)", "book": "", "page": "", "license": "", "rules": "2014", "revision": 1},
                       "quantity": 1, "weight": {"value": spec.get("weight", 0), "units": "lb"}, "price": {"value": spec.get("price", 0), "denomination": "gp"},
                       "rarity": spec.get("rarity", ""), "identified": True, "type": {"value": "gear", "subtype": ""}, "properties": [], "container": None, "activities": {}},
            "effects": [], "sort": 0, "ownership": {"default": 0},
            "flags": {"levels-3d-preview": {"model3d": f"assets/varrenmoor-3d/{DEFAULT_FOLDER}/Items/{model_file}"}}}


def create(spec, dry=False, log=print):
    model_file = spec.get("model") or build_model(spec, dry, log)
    it = build_item_doc(spec, model_file)
    if dry:
        log(json.dumps({"name": it["name"], "model": model_file, "folder": spec.get("folder")}, indent=1))
        return it, None, model_file
    it["folder"] = folder_id(spec.get("folder", "Quest Items (Side Quests)"), "Item")
    uuid = bridge("create", documentName="Item", data=it)["uuid"]
    log(f"item created: {uuid}")
    return it, uuid, model_file


def model_size(model_file):
    side = next(OUT.rglob(model_file.replace(".glb", ".scene.json")), None)
    return json.loads(side.read_text())["size_m"] if side else [0.1, 0.1, 0.05]


def place_tile(item_uuid, scene_uuid, x, y, z, model_file, wall=False, facing="n", scale=3.0, log=print):
    """Place an item's model as a Tile. z = height (m) of the surface it rests on (0.1 = floor). wall=True: z is the plate's CENTRE height and the model
    stands upright with its face toward +y (north); facing n/s/e/w turns it (n verified, the others untested). `scale` enlarges it so it is readable."""
    fr = scene_frame(scene_uuid)
    sx, sy, sz = model_size(model_file)
    px, py, el = to_scene(fr, x, y, z - (sz / 2 * scale if wall else 0))
    tile = {"x": px, "y": py, "width": max(4, round(sx * fr["pxm_x"] * scale)), "height": max(4, round(sy * fr["pxm_y"] * scale)), "elevation": el,
            "rotation": {"n": 0, "s": 180, "e": 90, "w": 270}[facing], "texture": {"src": "modules/levels-3d-preview/assets/blank.webp"},
            "flags": {"levels-3d-preview": {"model3d": f"assets/varrenmoor-3d/{DEFAULT_FOLDER}/Items/{model_file}", "autoGround": True, "autoCenter": False,
                                            "depth": max(2, round(sz * fr["pxm_z"] * scale))}, "varrenmoor": {"itemUuid": item_uuid}}}
    r = bridge("create", documentName="Tile", parentUuid=scene_uuid, data=tile)
    log(f"tile placed: {r['uuid']} at ({px},{py}) elevation {el} ft")
    return r["uuid"]
